# config/cable.yml

development:
  adapter: async
  url: redis://localhost:6379/1
  channel_prefix: your_app_development

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: your_app_production
  channel_class: 'ApplicationCable::Channel'
